feature/paywall-use-case
fingerprintjs/fingerprintjs-pro-use-cases pull request #17
Opened 2022-08-09 17:34 UTC by TheUnderScorer

2022-08-09 18:59 UTC, ilfa approved these changes

2022-09-14 14:27 UTC, makma requested changes
Great work @Przemo, just a couple of minor things to adjust, thank you! :)
- Change count of articles from 3 to 2 (fewer steps for users in the demo, better and easier to understand the showcase)
- Use some real content instead of lorem ipsum e.g. from https://fingerprint.com/blog/. Just a couple of first paragraphs should be sufficient. It's hard to remember visited articles with lorem ipsum, therefore more real-world content should be IMO better. Alternatively, you can use http://bullshitipsum.com/. Up to you.
- An error after viewing an article after limitation just floats in the middle of the screen. Do we have another alternative? This looks weird to me...
- `This page demonstrates paywall implementation using Fingerprint PRO`. -> It's `Fingerprint Pro`, not `Fingerprint PRO`
- Add personalization use case and paywall use case to the readme.md
- Remove warning from the readme.
- Add a link to the readme referencing our content https://fingerprint.com/use-cases/

2022-09-14 14:27 UTC, makma commented on api/paywall/article-views.js
> + * Checks if given visitor has exceeded his daily limit of free article views.
```suggestion
 * Checks if the given visitor has exceeded his daily limit of free article views.
```

2022-09-14 14:27 UTC, makma commented on api/paywall/article-views.js
> + * Saves article view into database. If it already exists, we update its timestamp.
```suggestion
 * Saves article view into the database. If it already exists, we update its timestamp.
```

2022-09-14 14:27 UTC, makma commented on api/paywall/articles.js
> + * Mock articles "database". In a real world, these articles could be fetched from anywhere.
```suggestion
 * Mock articles "database". In the real world, these articles could be fetched from anywhere.
```

2022-09-14 14:27 UTC, makma commented on api/paywall/paywall-endpoint.js
> +const loanChecks = [
probably not `loanChecks` + comment

2022-09-14 14:27 UTC, makma commented on api/paywall/paywall-endpoint.js
> +// Provides common logic used in paywall use-case
```suggestion
// Provides common logic used in the paywall use-case
```

2022-09-14 14:27 UTC, makma commented on api/paywall/paywall-endpoint.js
> +            // No need to report suspicious activity for this error
Good catch and comment!

2022-09-14 14:27 UTC, makma commented on pages/api/paywall/article/[id].js
> + * Fetches article by its ID. Supports paywall logic, which means that we keep track how many articles were viewed by given user.
```suggestion
 * Fetches article by its ID. Supports paywall logic, which means that we keep track of how many articles were viewed by a given user.
```

2022-09-14 14:27 UTC, makma commented on pages/api/paywall/article/[id].js
> + * If user has exceeded limit of articles that he can view for free, we return an error.
```suggestion
 * If a user has exceeded limit of articles that he can view for free, we return an error.
```

2022-09-14 14:27 UTC, makma commented on pages/api/paywall/get-articles.js
> + * Returns articles with trimmed description from the database.
```suggestion
 * Returns articles with trimmed descriptions from the database.
```

2022-09-18 16:37 UTC, makma approved these changes
Thank you @TheUnderScorer!

2022-09-18 16:37 UTC, merged